### PR TITLE
Add Nix Board Fireside Chat

### PR DESCRIPTION
**Pull request by infinisil**
Was missing. I shifted the numbers to be in sequence again

### CODE REVIEW

**Comment by kip93** [comment]
To not have you rebase a 9 month old PR, I did it myself on 99509dd

**Comment by infinisil** [comment]
Thanks!

**Comment by infinisil** [comment]
Oh looks like there was a mistake, https://github.com/nixcon/NixConContent/tree/main/NixCon%202022%20-%20Paris/09%20-%20Nix%20Board%20Fireside%20Chat#readme doesn't have the correct links and title. See this PR for the right oness

**Comment by kip93** [comment]
Oh no, the good old copy paste mistake. I'll fix it!

**Pull request closed without merging**
